name: AWS Deployment
on:
  push
permissions:
  id-token: write
  contents: read
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      # Clone Repo
      - name: Git clone the repository
        uses: actions/checkout@v5
      # Retrieve AWS Credentials
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: sessionrole
          aws-region: ${{ secrets.AWS_REGION }}
      # Install NPM
      - name: Install modules
        run: npm ci
      # Create production files/distribution
      - name: Build application
        run: npm run build
      # Update S3 Static Site Bucket
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.AWS_BUCKET_NAME }}
      # Invalidate old site
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION }} --paths "/*"
